/* Generated By:JJTree: Do not edit this line. ASTAssignOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import java.util.ArrayList;

public
class ASTAssignOperator extends SimpleNode {
  public ASTAssignOperator(int id) {
    super(id);
  }

  public ASTAssignOperator(Jmm p, int id) {
    super(p, id);
  }

  @Override
  public void analyzeSemantics(ArrayList<SymbolTable> symbolTables, ArrayList<String> errors){

    for(int i = 0; i < this.jjtGetNumChildren(); i++){
      
      this.jjtGetChild(i).setMethod(this.getMethod());
      this.jjtGetChild(i).analyzeSemantics(symbolTables, errors);
      

    }

  }
}
/* JavaCC - OriginalChecksum=164d1b24e984d94d6d47cfba74c1516a (do not edit this line) */
