/* Generated By:JJTree: Do not edit this line. ASTAuxExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import java.util.ArrayList;

public
class ASTAuxExpression extends SimpleNode {
  public ASTAuxExpression(int id) {
    super(id);
  }

  public ASTAuxExpression(Jmm p, int id) {
    super(p, id);
  }

  @Override
  public void analyzeSemantics(ArrayList<SymbolTable> symbolTables, ArrayList<String> errors){

    for(int i = 0; i < this.jjtGetNumChildren(); i++){
      
      this.jjtGetChild(i).setMethod(this.getMethod());
      this.jjtGetChild(i).analyzeSemantics(symbolTables, errors);
      

    }

  }

}
/* JavaCC - OriginalChecksum=189e0046d9ae788d782f02e8b75cbdba (do not edit this line) */
