/* Generated By:JJTree: Do not edit this line. ASTElse.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

import java.util.ArrayList;
public
class ASTElse extends SimpleNode {
  public ASTElse(int id) {
    super(id);
  }

  public ASTElse(Jmm p, int id) {
    super(p, id);
  }

  @Override
  public void analyzeSemantics(ArrayList<SymbolTable> symbolTables, ArrayList<String> errors){

    for(int i = 0; i < this.jjtGetNumChildren(); i++){
      
      this.jjtGetChild(i).setMethod(this.getMethod());
      //this.jjtGetChild(i).setArguments(this.getArguments());
      this.jjtGetChild(i).analyzeSemantics(symbolTables, errors);

    }

  }

  @Override
  public String getCode(ArrayList<SymbolTable> symbolTables, SimpleNode stackMethod){

    StringBuilder code = new StringBuilder("");

    int elseIndex = this.jjtGetParent().getIndex();

    code.append("else_" + elseIndex + ":\n");

    for(int i = 0; i < this.jjtGetNumChildren(); i++){

      code.append(this.jjtGetChild(i).getCode(symbolTables, stackMethod));

    }

    code.append("endif_" + elseIndex + ":\n");

    this.jjtGetParent().incrementIndex();

    return code.toString();
  }

}
/* JavaCC - OriginalChecksum=a6e365ef44fbcd576c68f1984d9269b9 (do not edit this line) */
