/* Generated By:JJTree: Do not edit this line. ASTInt.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import java.util.ArrayList;

public
class ASTInt extends SimpleNode {
  public ASTInt(int id) {
    super(id);
  }

  public ASTInt(Jmm p, int id) {
    super(p, id);
  }

  @Override
  public void analyzeSemantics(ArrayList<SymbolTable> symbolTables, ArrayList<String> errors){

    for(int i = 0; i < this.jjtGetNumChildren(); i++){
      
      this.jjtGetChild(i).analyzeSemantics(symbolTables, errors);

    }

  }

}
/* JavaCC - OriginalChecksum=0644346b01781537d372e3c1e4f3e846 (do not edit this line) */
