/* Generated By:JJTree: Do not edit this line. ASTParseRoot.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import java.util.ArrayList;

public
class ASTParseRoot extends SimpleNode {
  public ASTParseRoot(int id) {
    super(id);
  }

  public ASTParseRoot(Jmm p, int id) {
    super(p, id);
  }

  @Override
  public void analyzeSemantics(ArrayList<SymbolTable> symbolTables, ArrayList<String> errors){

    for(int i = 0; i < this.jjtGetNumChildren(); i++){
      
      this.jjtGetChild(i).analyzeSemantics(symbolTables, errors);

    }

  }

  @Override
  public String getCode(ArrayList<SymbolTable> symbolTables, SimpleNode stackMethod){

    StringBuilder code = new StringBuilder("");

    for(int i = 0; i < this.jjtGetNumChildren(); i++){

      code.append(this.jjtGetChild(i).getCode(symbolTables, stackMethod));

    }

    return code.toString();

  }

}
/* JavaCC - OriginalChecksum=4f6be5a718bc12c653478bd43127594a (do not edit this line) */
