/* Generated By:JavaCC: Do not edit this line. JmmTreeConstants.java Version 6.0_1 */
public interface JmmTreeConstants
{
  public int JJTPARSEROOT = 0;
  public int JJTIMPORTDECLARATION = 1;
  public int JJTPARAMLIST = 2;
  public int JJTCLASSDECLARATION = 3;
  public int JJTEXTENDS = 4;
  public int JJTVARDECLARATION = 5;
  public int JJTVOID = 6;
  public int JJTMETHOD = 7;
  public int JJTRETURN = 8;
  public int JJTMAIN = 9;
  public int JJTARRAY = 10;
  public int JJTBOOLEAN = 11;
  public int JJTINT = 12;
  public int JJTWHILE = 13;
  public int JJTASSIGN = 14;
  public int JJTIF = 15;
  public int JJTELSE = 16;
  public int JJTNEWARRAY = 17;
  public int JJTNEWCLASS = 18;
  public int JJTNOT = 19;
  public int JJTARRAYACCESS = 20;
  public int JJTLENGTH = 21;
  public int JJTDOT = 22;
  public int JJTFUNCTIONCALL = 23;
  public int JJTVALUE = 24;
  public int JJTAND = 25;
  public int JJTLESS = 26;
  public int JJTSUM = 27;
  public int JJTSUB = 28;
  public int JJTMULT = 29;
  public int JJTDIV = 30;
  public int JJTARGS = 31;
  public int JJTIDENTIFIER = 32;


  public String[] jjtNodeName = {
    "ParseRoot",
    "ImportDeclaration",
    "ParamList",
    "ClassDeclaration",
    "Extends",
    "VarDeclaration",
    "void",
    "Method",
    "Return",
    "Main",
    "Array",
    "Boolean",
    "Int",
    "While",
    "Assign",
    "If",
    "Else",
    "NewArray",
    "NewClass",
    "Not",
    "ArrayAccess",
    "Length",
    "Dot",
    "FunctionCall",
    "Value",
    "And",
    "Less",
    "Sum",
    "Sub",
    "Mult",
    "Div",
    "Args",
    "Identifier",
  };
}
/* JavaCC - OriginalChecksum=f623654338a1f9b6d84a91e83ddb658f (do not edit this line) */
